"""add date column to mealplans table

Revision ID: 9d023bfdf685
Revises: fa26656da0c7
Create Date: 2024-06-21 11:55:20.764408

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '9d023bfdf685'
down_revision = 'fa26656da0c7'
branch_labels = None
depends_on = None

schema = SCHEMA if environment == 'production' else None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mealplans', schema=schema) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mealplans', schema=schema) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
