"""add description to recipes table

Revision ID: fa26656da0c7
Revises: bf8746279dfb
Create Date: 2024-05-31 16:02:58.402031

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'fa26656da0c7'
down_revision = 'bf8746279dfb'
branch_labels = None
depends_on = None

schema = SCHEMA if environment == 'production' else None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=schema) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=schema) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
